# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(default='', max_length=8)),
                ('address', models.CharField(max_length=140, verbose_name='Address')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('city', models.CharField(max_length=140, verbose_name='City')),
                ('district', models.CharField(max_length=140, verbose_name='District')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='Rooms')),
                ('util_area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Util Area')),
                ('total_area', models.PositiveSmallIntegerField(verbose_name='Total Area')),
                ('title', models.CharField(max_length=140, verbose_name='Title')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('rent_price', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Valor do aluguel')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('category', smart_selects.db_fields.ChainedForeignKey(chained_field='property_type', chained_model_field='property_type', on_delete=django.db.models.deletion.CASCADE, to='properties.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'verbose_name': 'Property',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Type of Property')),
            ],
            options={
                'verbose_name_plural': 'Type of Properties',
                'verbose_name': 'Type of Property',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyType'),
        ),
        migrations.AddField(
            model_name='category',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyType'),
        ),
    ]
