# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='cep',
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Property Value'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=80, verbose_name='State'),
        ),
    ]
