# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 07:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20170617_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(max_length=40, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='property',
            name='prefered_radius',
            field=models.IntegerField(default=5, help_text='in kilometers'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Property Value'),
        ),
    ]
