# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 03:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20170624_0744'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='property',
            managers=[
                ('gis', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
