# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20170701_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Property Value'),
        ),
    ]
