export const LOAD_PROPERTY_TYPE = 'XcelTrip/ListRoom/LOAD_PROPERTY_TYPE';
export const LOAD_PROPERTY_TYPE_SUCCESS = 'XcelTrip/ListRoom/LOAD_PROPERTY_TYPE_SUCCESS';
export const LOAD_PROPERTY_TYPE_FAILURE = 'XcelTrip/ListRoom/LOAD_PROPERTY_TYPE_FAILURE';
export const LIST_PROPERTY = 'XcelTrip/ListRoom/LIST_PROPERTY';
export const LIST_PROPERTY_SUCCESS = 'XcelTrip/ListRoom/LIST_PROPERTY_SUCCESS';
export const LIST_PROPERTY_FAILURE = 'XcelTrip/ListRoom/LIST_PROPERTY_FAILURE';
